name: Generate PKL Files

on:
  workflow_dispatch:
    inputs:
      match_index:
        description: 'Match index from match.csv'
        required: true
        type: number
        default: 12

  # Manual trigger from GitHub UI
  # or use schedule if you want it automatic:
  # schedule:
  #   - cron: '0 0 * * *'  # daily at midnight

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # adjust to your version
    - name: Install Deno (JS runtime for yt-dlp)
      run: |
          curl -fsSL https://deno.land/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
#    - name: Setup cookies
#      run: |
#            echo "${{ secrets.YOUTUBE_COOKIES }}" | base64 -d > cookies.txt
#
#    - name: Debug cookies file
#      run: |
#            echo "=== First 5 lines of cookies.txt ==="
#            head -n 5 cookies.txt
#            echo ""
#            echo "=== File size ==="
#            wc -l cookies.txt

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        pip install -r requirements.txt
        pip install --upgrade yt-dlp
    

    - name: Run script
      run: python main.py -m ${{ inputs.match_index }}

    - name: Upload PKL files
      uses: actions/upload-artifact@v4
      with:
        name: pkl-files-match-${{ inputs.match_index }}
        path: '*.pkl'